CREATE TABLE amazon_redshift_ingestion (
    "sku" TEXT,
    "offer_term_code" TEXT,
    "rate_code" TEXT PRIMARY KEY,
    "term_type" TEXT,
    "price_description" TEXT,
    "effective_date" DATE,
    "starting_range" TEXT,
    "ending_range" TEXT,
    "unit" TEXT,
    "price_per_unit" DECIMAL(20,10),
    "currency" TEXT,
    "lease_contract_length" INTEGER,
    "purchase_option" TEXT,
    "offering_class" TEXT,
    "product_family" TEXT,
    "service_code" TEXT,
    "description" TEXT,
    "location" TEXT,
    "location_type" TEXT,
    "instance_type" TEXT,
    "current_generation" TEXT,
    "v_cpu" TEXT,
    "memory" TEXT,
    "storage" TEXT,
    "i_o" TEXT,
    "storage_media" TEXT,
    "usage_type" TEXT,
    "operation" TEXT,
    "concurrency_scaling_free_usage" TEXT,
    "ecu" TEXT,
    "region_code" TEXT,
    "service_name" TEXT,
    "usage_family" TEXT
);
CREATE INDEX amazon_redshift_20260423193445_sku ON amazon_redshift_ingestion (sku);
CREATE INDEX amazon_redshift_20260423193445_region_code ON amazon_redshift_ingestion (region_code);
