CREATE TABLE IF NOT EXISTS "AmazonBraket_ingestion" (
    "sku" TEXT,
    "offer_term_code" TEXT,
    "rate_code" TEXT,
    "term_type" TEXT,
    "price_description" TEXT,
    "effective_date" DATE,
    "starting_range" TEXT,
    "ending_range" TEXT,
    "unit" TEXT,
    "price_per_unit" DECIMAL(20,10),
    "currency" TEXT,
    "related_to" TEXT,
    "product_family" TEXT,
    "service_code" TEXT,
    "location" TEXT,
    "location_type" TEXT,
    "instance_type" TEXT,
    "v_cpu" TEXT,
    "memory" TEXT,
    "volume_type" TEXT,
    "usage_type" TEXT,
    "operation" TEXT,
    "compute_type" TEXT,
    "device_name" TEXT,
    "device_provider" TEXT,
    "operation_outcome" TEXT,
    "product_type" TEXT,
    "provider" TEXT,
    "region_code" TEXT,
    "service_name" TEXT,
    "simulator_name" TEXT,
    "type" TEXT,
    "version" TEXT,
    "pricing_region" TEXT NOT NULL,
    PRIMARY KEY (rate_code, pricing_region)
);
CREATE INDEX IF NOT EXISTS AmazonBraket_20260407184508_sku ON "AmazonBraket_ingestion" ("sku");
CREATE INDEX IF NOT EXISTS AmazonBraket_20260407184508_region_code ON "AmazonBraket_ingestion" ("region_code");
CREATE INDEX IF NOT EXISTS AmazonBraket_20260407184508_pricing_region ON "AmazonBraket_ingestion" ("pricing_region");
