CREATE TABLE IF NOT EXISTS "AmazonRDS_ingestion" (
    "sku" TEXT,
    "offer_term_code" TEXT,
    "rate_code" TEXT,
    "term_type" TEXT,
    "price_description" TEXT,
    "effective_date" DATE,
    "starting_range" TEXT,
    "ending_range" TEXT,
    "unit" TEXT,
    "price_per_unit" DECIMAL(20,10),
    "currency" TEXT,
    "related_to" TEXT,
    "lease_contract_length" TEXT,
    "purchase_option" TEXT,
    "offering_class" TEXT,
    "product_family" TEXT,
    "service_code" TEXT,
    "location" TEXT,
    "location_type" TEXT,
    "instance_type" TEXT,
    "current_generation" TEXT,
    "instance_family" TEXT,
    "v_cpu" TEXT,
    "physical_processor" TEXT,
    "clock_speed" TEXT,
    "memory" TEXT,
    "storage" TEXT,
    "network_performance" TEXT,
    "processor_architecture" TEXT,
    "storage_media" TEXT,
    "volume_type" TEXT,
    "min_volume_size" TEXT,
    "max_volume_size" TEXT,
    "engine_code" TEXT,
    "database_engine" TEXT,
    "database_edition" TEXT,
    "license_model" TEXT,
    "deployment_option" TEXT,
    "group" TEXT,
    "group_description" TEXT,
    "usage_type" TEXT,
    "operation" TEXT,
    "acu" TEXT,
    "dedicated_ebs_throughput" TEXT,
    "deployment_model" TEXT,
    "engine_major_version" TEXT,
    "engine_media_type" TEXT,
    "enhanced_networking_supported" TEXT,
    "extended_support_pricing_year" TEXT,
    "instance_type_family" TEXT,
    "limitless_preview" TEXT,
    "normalization_size_factor" TEXT,
    "processor_features" TEXT,
    "region_code" TEXT,
    "service_name" TEXT,
    "unbundled_licensing" TEXT,
    "volume_name" TEXT,
    "windows_license_multiplier" TEXT,
    "pricing_region" TEXT NOT NULL,
    PRIMARY KEY (rate_code, pricing_region)
);
CREATE INDEX IF NOT EXISTS AmazonRDS_20260508211654_sku ON "AmazonRDS_ingestion" ("sku");
CREATE INDEX IF NOT EXISTS AmazonRDS_20260508211654_region_code ON "AmazonRDS_ingestion" ("region_code");
CREATE INDEX IF NOT EXISTS AmazonRDS_20260508211654_pricing_region ON "AmazonRDS_ingestion" ("pricing_region");
