CREATE TABLE amazon_app_stream_ingestion (
    "sku" TEXT,
    "offer_term_code" TEXT,
    "rate_code" TEXT PRIMARY KEY,
    "term_type" TEXT,
    "price_description" TEXT,
    "effective_date" DATE,
    "starting_range" TEXT,
    "ending_range" TEXT,
    "unit" TEXT,
    "price_per_unit" DECIMAL(20,10),
    "currency" TEXT,
    "product_family" TEXT,
    "service_code" TEXT,
    "location" TEXT,
    "location_type" TEXT,
    "instance_type" TEXT,
    "instance_family" TEXT,
    "v_cpu" TEXT,
    "operating_system" TEXT,
    "license_model" TEXT,
    "usage_type" TEXT,
    "operation" TEXT,
    "application" TEXT,
    "gpu" TEXT,
    "instance_function" TEXT,
    "license_model_description" TEXT,
    "memory_gi_b" TEXT,
    "multi_session" TEXT,
    "os_license_model" TEXT,
    "region_code" TEXT,
    "service_name" TEXT,
    "video_memory_gi_b" TEXT
);
CREATE INDEX amazon_app_stream_20260108165923_sku ON amazon_app_stream_ingestion (sku);
CREATE INDEX amazon_app_stream_20260108165923_region_code ON amazon_app_stream_ingestion (region_code);
