CREATE TABLE amazon_omics_ingestion (
    "sku" TEXT,
    "offer_term_code" TEXT,
    "rate_code" TEXT PRIMARY KEY,
    "term_type" TEXT,
    "price_description" TEXT,
    "effective_date" DATE,
    "starting_range" TEXT,
    "ending_range" TEXT,
    "unit" TEXT,
    "price_per_unit" DECIMAL(20,10),
    "currency" TEXT,
    "product_family" TEXT,
    "service_code" TEXT,
    "location" TEXT,
    "location_type" TEXT,
    "v_cpu" TEXT,
    "memory" TEXT,
    "storage_class" TEXT,
    "group" TEXT,
    "group_description" TEXT,
    "usage_type" TEXT,
    "operation" TEXT,
    "analytics_type" TEXT,
    "datastore_type" TEXT,
    "gpu" TEXT,
    "gpu_memory" TEXT,
    "omics_instance_type" TEXT,
    "publisher" TEXT,
    "ready2_run_workflow_name" TEXT,
    "ready2_run_workflow_version" TEXT,
    "region_code" TEXT,
    "resource_type" TEXT,
    "service_name" TEXT,
    "workflow_type" TEXT
);
CREATE INDEX amazon_omics_20250903193809_sku ON amazon_omics_ingestion (sku);
CREATE INDEX amazon_omics_20250903193809_region_code ON amazon_omics_ingestion (region_code);
