CREATE TABLE amazon_elasti_cache_ingestion (
    "sku" TEXT,
    "offer_term_code" TEXT,
    "rate_code" TEXT PRIMARY KEY,
    "term_type" TEXT,
    "price_description" TEXT,
    "effective_date" DATE,
    "starting_range" TEXT,
    "ending_range" TEXT,
    "unit" TEXT,
    "price_per_unit" DECIMAL(20,10),
    "currency" TEXT,
    "lease_contract_length" INTEGER,
    "purchase_option" TEXT,
    "offering_class" TEXT,
    "product_family" TEXT,
    "service_code" TEXT,
    "location" TEXT,
    "location_type" TEXT,
    "instance_type" TEXT,
    "current_generation" TEXT,
    "instance_family" TEXT,
    "v_cpu" TEXT,
    "memory" TEXT,
    "network_performance" TEXT,
    "cache_engine" TEXT,
    "storage_media" TEXT,
    "transfer_type" TEXT,
    "usage_type" TEXT,
    "operation" TEXT,
    "normalization_size_factor" TEXT,
    "region_code" TEXT,
    "service_name" TEXT,
    "year_number" TEXT
);
CREATE INDEX amazon_elasti_cache_20260403221334_sku ON amazon_elasti_cache_ingestion (sku);
CREATE INDEX amazon_elasti_cache_20260403221334_region_code ON amazon_elasti_cache_ingestion (region_code);
