CREATE TABLE IF NOT EXISTS "AmazonSES_ingestion" (
    "sku" TEXT,
    "offer_term_code" TEXT,
    "rate_code" TEXT,
    "term_type" TEXT,
    "price_description" TEXT,
    "effective_date" DATE,
    "starting_range" TEXT,
    "ending_range" TEXT,
    "unit" TEXT,
    "price_per_unit" DECIMAL(20,10),
    "currency" TEXT,
    "related_to" TEXT,
    "product_family" TEXT,
    "service_code" TEXT,
    "description" TEXT,
    "location" TEXT,
    "location_type" TEXT,
    "origin" TEXT,
    "group" TEXT,
    "group_description" TEXT,
    "usage_type" TEXT,
    "operation" TEXT,
    "api_category" TEXT,
    "content_type" TEXT,
    "recipient" TEXT,
    "recipient_validation" TEXT,
    "region_code" TEXT,
    "service_name" TEXT,
    "pricing_region" TEXT NOT NULL,
    PRIMARY KEY (rate_code, pricing_region)
);
CREATE INDEX IF NOT EXISTS AmazonSES_20260428181824_sku ON "AmazonSES_ingestion" ("sku");
CREATE INDEX IF NOT EXISTS AmazonSES_20260428181824_region_code ON "AmazonSES_ingestion" ("region_code");
CREATE INDEX IF NOT EXISTS AmazonSES_20260428181824_pricing_region ON "AmazonSES_ingestion" ("pricing_region");
