CREATE TABLE IF NOT EXISTS "AmazonECS_ingestion" (
    "sku" TEXT,
    "offer_term_code" TEXT,
    "rate_code" TEXT,
    "term_type" TEXT,
    "price_description" TEXT,
    "effective_date" DATE,
    "starting_range" TEXT,
    "ending_range" TEXT,
    "unit" TEXT,
    "price_per_unit" DECIMAL(20,10),
    "currency" TEXT,
    "product_family" TEXT,
    "service_code" TEXT,
    "location" TEXT,
    "location_type" TEXT,
    "instance_type" TEXT,
    "tenancy" TEXT,
    "operating_system" TEXT,
    "usage_type" TEXT,
    "operation" TEXT,
    "cpu_architecture" TEXT,
    "cpu_type" TEXT,
    "external_instance_type" TEXT,
    "memory_type" TEXT,
    "region_code" TEXT,
    "resource" TEXT,
    "service_name" TEXT,
    "storage_type" TEXT,
    "pricing_region" TEXT NOT NULL,
    PRIMARY KEY (rate_code, pricing_region)
);
CREATE INDEX IF NOT EXISTS AmazonECS_20260216071830_sku ON "AmazonECS_ingestion" ("sku");
CREATE INDEX IF NOT EXISTS AmazonECS_20260216071830_region_code ON "AmazonECS_ingestion" ("region_code");
CREATE INDEX IF NOT EXISTS AmazonECS_20260216071830_pricing_region ON "AmazonECS_ingestion" ("pricing_region");
