CREATE TABLE IF NOT EXISTS "AmazonES_ingestion" (
    "sku" TEXT,
    "offer_term_code" TEXT,
    "rate_code" TEXT,
    "term_type" TEXT,
    "price_description" TEXT,
    "effective_date" DATE,
    "starting_range" TEXT,
    "ending_range" TEXT,
    "unit" TEXT,
    "price_per_unit" DECIMAL(20,10),
    "currency" TEXT,
    "lease_contract_length" TEXT,
    "purchase_option" TEXT,
    "offering_class" TEXT,
    "product_family" TEXT,
    "service_code" TEXT,
    "location" TEXT,
    "location_type" TEXT,
    "instance_type" TEXT,
    "current_generation" TEXT,
    "instance_family" TEXT,
    "v_cpu" TEXT,
    "storage" TEXT,
    "storage_media" TEXT,
    "usage_type" TEXT,
    "operation" TEXT,
    "compute_type" TEXT,
    "ecu" TEXT,
    "memory_gi_b" TEXT,
    "region_code" TEXT,
    "requests" TEXT,
    "service_name" TEXT,
    "pricing_region" TEXT NOT NULL,
    PRIMARY KEY (rate_code, pricing_region)
);
CREATE INDEX IF NOT EXISTS AmazonES_20260428033915_sku ON "AmazonES_ingestion" ("sku");
CREATE INDEX IF NOT EXISTS AmazonES_20260428033915_region_code ON "AmazonES_ingestion" ("region_code");
CREATE INDEX IF NOT EXISTS AmazonES_20260428033915_pricing_region ON "AmazonES_ingestion" ("pricing_region");
