CREATE TABLE amazon_cloud_watch_ingestion (
    "sku" TEXT,
    "offer_term_code" TEXT,
    "rate_code" TEXT PRIMARY KEY,
    "term_type" TEXT,
    "price_description" TEXT,
    "effective_date" DATE,
    "starting_range" TEXT,
    "ending_range" TEXT,
    "unit" TEXT,
    "price_per_unit" DECIMAL(20,10),
    "currency" TEXT,
    "related_to" TEXT,
    "product_family" TEXT,
    "service_code" TEXT,
    "location" TEXT,
    "location_type" TEXT,
    "storage_media" TEXT,
    "group" TEXT,
    "group_description" TEXT,
    "usage_type" TEXT,
    "operation" TEXT,
    "alarm_type" TEXT,
    "database_engine_type" TEXT,
    "instance_configuration_type" TEXT,
    "logs_destination" TEXT,
    "region_code" TEXT,
    "service_name" TEXT,
    "type" TEXT,
    "type_description" TEXT,
    "version" TEXT
);
CREATE INDEX amazon_cloud_watch_20260313174219_sku ON amazon_cloud_watch_ingestion (sku);
CREATE INDEX amazon_cloud_watch_20260313174219_region_code ON amazon_cloud_watch_ingestion (region_code);
