CREATE TABLE amazon_quick_sight_ingestion (
    "sku" TEXT,
    "offer_term_code" TEXT,
    "rate_code" TEXT PRIMARY KEY,
    "term_type" TEXT,
    "price_description" TEXT,
    "effective_date" DATE,
    "starting_range" TEXT,
    "ending_range" TEXT,
    "unit" TEXT,
    "price_per_unit" DECIMAL(20,10),
    "currency" TEXT,
    "product_family" TEXT,
    "service_code" TEXT,
    "location" TEXT,
    "location_type" TEXT,
    "group" TEXT,
    "group_description" TEXT,
    "usage_type" TEXT,
    "operation" TEXT,
    "edition" TEXT,
    "pack_size" TEXT,
    "q_present" TEXT,
    "region_code" TEXT,
    "service_name" TEXT,
    "subscription_type" TEXT,
    "usage_group" TEXT
);
CREATE INDEX amazon_quick_sight_20260403002404_sku ON amazon_quick_sight_ingestion (sku);
CREATE INDEX amazon_quick_sight_20260403002404_region_code ON amazon_quick_sight_ingestion (region_code);
