CREATE TABLE amazon_lex_ingestion (
    "sku" TEXT,
    "offer_term_code" TEXT,
    "rate_code" TEXT PRIMARY KEY,
    "term_type" TEXT,
    "price_description" TEXT,
    "effective_date" DATE,
    "starting_range" TEXT,
    "ending_range" TEXT,
    "unit" TEXT,
    "price_per_unit" DECIMAL(20,10),
    "currency" TEXT,
    "product_family" TEXT,
    "service_code" TEXT,
    "location" TEXT,
    "location_type" TEXT,
    "group" TEXT,
    "group_description" TEXT,
    "usage_type" TEXT,
    "operation" TEXT,
    "api_type" TEXT,
    "input_mode" TEXT,
    "language" TEXT,
    "learning_mode" TEXT,
    "output_mode" TEXT,
    "region_code" TEXT,
    "service_name" TEXT,
    "supported_modes" TEXT
);
CREATE INDEX amazon_lex_20251127021625_sku ON amazon_lex_ingestion (sku);
CREATE INDEX amazon_lex_20251127021625_region_code ON amazon_lex_ingestion (region_code);
