CREATE TABLE amazon_timestream_ingestion (
    "sku" TEXT,
    "offer_term_code" TEXT,
    "rate_code" TEXT PRIMARY KEY,
    "term_type" TEXT,
    "price_description" TEXT,
    "effective_date" DATE,
    "starting_range" TEXT,
    "ending_range" TEXT,
    "unit" TEXT,
    "price_per_unit" DECIMAL(20,10),
    "currency" TEXT,
    "product_family" TEXT,
    "service_code" TEXT,
    "description" TEXT,
    "location" TEXT,
    "location_type" TEXT,
    "instance_type" TEXT,
    "v_cpu" TEXT,
    "memory" TEXT,
    "storage" TEXT,
    "network_performance" TEXT,
    "storage_media" TEXT,
    "volume_type" TEXT,
    "min_volume_size" TEXT,
    "max_volume_size" TEXT,
    "engine_code" TEXT,
    "database_engine" TEXT,
    "license_model" TEXT,
    "deployment_option" TEXT,
    "usage_type" TEXT,
    "operation" TEXT,
    "disable_activation_confirmation_email" TEXT,
    "normalization_size_factor" TEXT,
    "region_code" TEXT,
    "service_name" TEXT
);
CREATE INDEX amazon_timestream_20260320000110_sku ON amazon_timestream_ingestion (sku);
CREATE INDEX amazon_timestream_20260320000110_region_code ON amazon_timestream_ingestion (region_code);
