CREATE TABLE IF NOT EXISTS "AmazonDocDB_ingestion" (
    "sku" TEXT,
    "offer_term_code" TEXT,
    "rate_code" TEXT,
    "term_type" TEXT,
    "price_description" TEXT,
    "effective_date" DATE,
    "starting_range" TEXT,
    "ending_range" TEXT,
    "unit" TEXT,
    "price_per_unit" DECIMAL(20,10),
    "currency" TEXT,
    "product_family" TEXT,
    "service_code" TEXT,
    "location" TEXT,
    "location_type" TEXT,
    "instance_type" TEXT,
    "current_generation" TEXT,
    "instance_family" TEXT,
    "v_cpu" TEXT,
    "physical_processor" TEXT,
    "clock_speed" TEXT,
    "memory" TEXT,
    "instance_storage" TEXT,
    "network_performance" TEXT,
    "processor_architecture" TEXT,
    "storage_media" TEXT,
    "volume_type" TEXT,
    "min_volume_size" TEXT,
    "max_volume_size" TEXT,
    "engine_code" TEXT,
    "database_engine" TEXT,
    "group" TEXT,
    "group_description" TEXT,
    "usage_type" TEXT,
    "operation" TEXT,
    "enhanced_networking_supported" TEXT,
    "instance_type_family" TEXT,
    "normalization_size_factor" TEXT,
    "region_code" TEXT,
    "service_name" TEXT,
    "storage_type" TEXT,
    "volume_optimization" TEXT,
    "pricing_region" TEXT NOT NULL,
    PRIMARY KEY (rate_code, pricing_region)
);
CREATE INDEX IF NOT EXISTS AmazonDocDB_20260507170359_sku ON "AmazonDocDB_ingestion" ("sku");
CREATE INDEX IF NOT EXISTS AmazonDocDB_20260507170359_region_code ON "AmazonDocDB_ingestion" ("region_code");
CREATE INDEX IF NOT EXISTS AmazonDocDB_20260507170359_pricing_region ON "AmazonDocDB_ingestion" ("pricing_region");
