CREATE TABLE IF NOT EXISTS "AmazonQuickSuite_ingestion" (
    "sku" TEXT,
    "offer_term_code" TEXT,
    "rate_code" TEXT PRIMARY KEY,
    "term_type" TEXT,
    "price_description" TEXT,
    "effective_date" DATE,
    "starting_range" TEXT,
    "ending_range" TEXT,
    "unit" TEXT,
    "price_per_unit" DECIMAL(20,10),
    "currency" TEXT,
    "service_code" TEXT,
    "location" TEXT,
    "location_type" TEXT,
    "usage_type" TEXT,
    "operation" TEXT,
    "feature_code_agent_hour" TEXT,
    "feature_code_index_capacity" TEXT,
    "feature_name_agent_hour" TEXT,
    "feature_name_index_capacity" TEXT,
    "feature_sku_agent_hour" TEXT,
    "feature_sku_index_capacity" TEXT,
    "overage_price_per_unit_agent_hour" TEXT,
    "overage_price_per_unit_index_capacity" TEXT,
    "plan_code" TEXT,
    "plan_family_code" TEXT,
    "plan_family_name" TEXT,
    "plan_name" TEXT,
    "region_code" TEXT,
    "service_name" TEXT,
    "usage_pooling_policy_agent_hour" TEXT,
    "usage_pooling_policy_index_capacity" TEXT,
    "usage_quota_agent_hour" TEXT,
    "usage_quota_index_capacity" TEXT,
    "usage_quota_unit_agent_hour" TEXT,
    "usage_quota_unit_index_capacity" TEXT
);
CREATE INDEX IF NOT EXISTS AmazonQuickSuite_20260428154623_sku ON "AmazonQuickSuite_ingestion" ("sku");
CREATE INDEX IF NOT EXISTS AmazonQuickSuite_20260428154623_region_code ON "AmazonQuickSuite_ingestion" ("region_code");
