CREATE TABLE IF NOT EXISTS "AmazonElastiCache_ingestion" (
    "sku" TEXT,
    "offer_term_code" TEXT,
    "rate_code" TEXT PRIMARY KEY,
    "term_type" TEXT,
    "price_description" TEXT,
    "effective_date" DATE,
    "starting_range" TEXT,
    "ending_range" TEXT,
    "unit" TEXT,
    "price_per_unit" DECIMAL(20,10),
    "currency" TEXT,
    "lease_contract_length" TEXT,
    "purchase_option" TEXT,
    "offering_class" TEXT,
    "product_family" TEXT,
    "service_code" TEXT,
    "location" TEXT,
    "location_type" TEXT,
    "instance_type" TEXT,
    "current_generation" TEXT,
    "instance_family" TEXT,
    "v_cpu" TEXT,
    "memory" TEXT,
    "network_performance" TEXT,
    "cache_engine" TEXT,
    "storage_media" TEXT,
    "transfer_type" TEXT,
    "usage_type" TEXT,
    "operation" TEXT,
    "normalization_size_factor" TEXT,
    "region_code" TEXT,
    "service_name" TEXT,
    "year_number" TEXT
);
CREATE INDEX IF NOT EXISTS AmazonElastiCache_20260507182426_sku ON "AmazonElastiCache_ingestion" ("sku");
CREATE INDEX IF NOT EXISTS AmazonElastiCache_20260507182426_region_code ON "AmazonElastiCache_ingestion" ("region_code");
