CREATE TABLE amazon_mq_ingestion (
    "sku" TEXT,
    "offer_term_code" TEXT,
    "rate_code" TEXT PRIMARY KEY,
    "term_type" TEXT,
    "price_description" TEXT,
    "effective_date" DATE,
    "starting_range" TEXT,
    "ending_range" TEXT,
    "unit" TEXT,
    "price_per_unit" DECIMAL(20,10),
    "currency" TEXT,
    "product_family" TEXT,
    "service_code" TEXT,
    "location" TEXT,
    "location_type" TEXT,
    "instance_type" TEXT,
    "v_cpu" TEXT,
    "clock_speed" TEXT,
    "memory" TEXT,
    "network_performance" TEXT,
    "storage_class" TEXT,
    "provisioned" TEXT,
    "license_model" TEXT,
    "deployment_option" TEXT,
    "usage_type" TEXT,
    "operation" TEXT,
    "broker_engine" TEXT,
    "cross_region_data_replication" TEXT,
    "enhanced_networking_support" TEXT,
    "normalization_size_factor" TEXT,
    "region_code" TEXT,
    "service_name" TEXT
);
CREATE INDEX amazon_mq_20251118015856_sku ON amazon_mq_ingestion (sku);
CREATE INDEX amazon_mq_20251118015856_region_code ON amazon_mq_ingestion (region_code);
