CREATE TABLE amazon_deadline_ingestion (
    "sku" TEXT,
    "offer_term_code" TEXT,
    "rate_code" TEXT PRIMARY KEY,
    "term_type" TEXT,
    "price_description" TEXT,
    "effective_date" DATE,
    "starting_range" TEXT,
    "ending_range" TEXT,
    "unit" TEXT,
    "price_per_unit" DECIMAL(20,10),
    "currency" TEXT,
    "product_family" TEXT,
    "service_code" TEXT,
    "location" TEXT,
    "location_type" TEXT,
    "instance_type" TEXT,
    "instance_family" TEXT,
    "v_cpu" TEXT,
    "memory" TEXT,
    "operating_system" TEXT,
    "endpoint_type" TEXT,
    "usage_type" TEXT,
    "operation" TEXT,
    "instance" TEXT,
    "licensed_product" TEXT,
    "region_code" TEXT,
    "service_name" TEXT,
    "worker_location" TEXT
);
CREATE INDEX amazon_deadline_20260312184105_sku ON amazon_deadline_ingestion (sku);
CREATE INDEX amazon_deadline_20260312184105_region_code ON amazon_deadline_ingestion (region_code);
