CREATE TABLE amazon_vpc_ingestion (
    "sku" TEXT,
    "offer_term_code" TEXT,
    "rate_code" TEXT PRIMARY KEY,
    "term_type" TEXT,
    "price_description" TEXT,
    "effective_date" DATE,
    "starting_range" TEXT,
    "ending_range" TEXT,
    "unit" TEXT,
    "price_per_unit" DECIMAL(20,10),
    "currency" TEXT,
    "product_family" TEXT,
    "service_code" TEXT,
    "location" TEXT,
    "location_type" TEXT,
    "endpoint_type" TEXT,
    "group" TEXT,
    "group_description" TEXT,
    "transfer_type" TEXT,
    "from_location" TEXT,
    "from_location_type" TEXT,
    "to_location" TEXT,
    "to_location_type" TEXT,
    "usage_type" TEXT,
    "operation" TEXT,
    "attachment_type" TEXT,
    "from_region_code" TEXT,
    "region_code" TEXT,
    "service_name" TEXT,
    "to_region_code" TEXT,
    "vpn_type" TEXT
);
CREATE INDEX amazon_vpc_20260426222652_sku ON amazon_vpc_ingestion (sku);
CREATE INDEX amazon_vpc_20260426222652_region_code ON amazon_vpc_ingestion (region_code);
