CREATE TABLE amazon_work_spaces_ingestion (
    "sku" TEXT,
    "offer_term_code" TEXT,
    "rate_code" TEXT PRIMARY KEY,
    "term_type" TEXT,
    "price_description" TEXT,
    "effective_date" DATE,
    "starting_range" TEXT,
    "ending_range" TEXT,
    "unit" TEXT,
    "price_per_unit" DECIMAL(20,10),
    "currency" TEXT,
    "related_to" TEXT,
    "product_family" TEXT,
    "service_code" TEXT,
    "location" TEXT,
    "location_type" TEXT,
    "v_cpu" TEXT,
    "memory" TEXT,
    "storage" TEXT,
    "operating_system" TEXT,
    "group" TEXT,
    "group_description" TEXT,
    "usage_type" TEXT,
    "operation" TEXT,
    "bundle" TEXT,
    "bundle_description" TEXT,
    "bundle_group" TEXT,
    "license" TEXT,
    "pricing_unit" TEXT,
    "region_code" TEXT,
    "resource_type" TEXT,
    "root_volume" TEXT,
    "running_mode" TEXT,
    "service_name" TEXT,
    "software_included" TEXT,
    "user_volume" TEXT
);
CREATE INDEX amazon_work_spaces_20260417024731_sku ON amazon_work_spaces_ingestion (sku);
CREATE INDEX amazon_work_spaces_20260417024731_region_code ON amazon_work_spaces_ingestion (region_code);
