CREATE TABLE amazon_neptune_ingestion (
    "sku" TEXT,
    "offer_term_code" TEXT,
    "rate_code" TEXT PRIMARY KEY,
    "term_type" TEXT,
    "price_description" TEXT,
    "effective_date" DATE,
    "starting_range" TEXT,
    "ending_range" TEXT,
    "unit" TEXT,
    "price_per_unit" DECIMAL(20,10),
    "currency" TEXT,
    "product_family" TEXT,
    "service_code" TEXT,
    "location" TEXT,
    "location_type" TEXT,
    "instance_type" TEXT,
    "current_generation" TEXT,
    "instance_family" TEXT,
    "v_cpu" TEXT,
    "physical_processor" TEXT,
    "clock_speed" TEXT,
    "memory" TEXT,
    "storage" TEXT,
    "network_performance" TEXT,
    "processor_architecture" TEXT,
    "storage_media" TEXT,
    "volume_type" TEXT,
    "min_volume_size" TEXT,
    "max_volume_size" TEXT,
    "engine_code" TEXT,
    "database_engine" TEXT,
    "license_model" TEXT,
    "deployment_option" TEXT,
    "group" TEXT,
    "group_description" TEXT,
    "usage_type" TEXT,
    "operation" TEXT,
    "dedicated_ebs_throughput" TEXT,
    "enhanced_networking_supported" TEXT,
    "m_ncu" TEXT,
    "normalization_size_factor" TEXT,
    "region_code" TEXT,
    "service_name" TEXT
);
CREATE INDEX amazon_neptune_20260313140701_sku ON amazon_neptune_ingestion (sku);
CREATE INDEX amazon_neptune_20260313140701_region_code ON amazon_neptune_ingestion (region_code);
