CREATE TABLE IF NOT EXISTS "AmazonS3_ingestion" (
    "sku" TEXT,
    "offer_term_code" TEXT,
    "rate_code" TEXT,
    "term_type" TEXT,
    "price_description" TEXT,
    "effective_date" DATE,
    "starting_range" TEXT,
    "ending_range" TEXT,
    "unit" TEXT,
    "price_per_unit" DECIMAL(20,10),
    "currency" TEXT,
    "product_family" TEXT,
    "service_code" TEXT,
    "location" TEXT,
    "location_type" TEXT,
    "availability" TEXT,
    "storage_class" TEXT,
    "volume_type" TEXT,
    "fee_code" TEXT,
    "fee_description" TEXT,
    "group" TEXT,
    "group_description" TEXT,
    "transfer_type" TEXT,
    "from_location" TEXT,
    "from_location_type" TEXT,
    "to_location" TEXT,
    "to_location_type" TEXT,
    "usage_type" TEXT,
    "operation" TEXT,
    "durability" TEXT,
    "from_region_code" TEXT,
    "overhead" TEXT,
    "region_code" TEXT,
    "service_name" TEXT,
    "to_region_code" TEXT,
    "pricing_region" TEXT NOT NULL,
    PRIMARY KEY (rate_code, pricing_region)
);
CREATE INDEX IF NOT EXISTS AmazonS3_20260427212459_sku ON "AmazonS3_ingestion" ("sku");
CREATE INDEX IF NOT EXISTS AmazonS3_20260427212459_region_code ON "AmazonS3_ingestion" ("region_code");
CREATE INDEX IF NOT EXISTS AmazonS3_20260427212459_pricing_region ON "AmazonS3_ingestion" ("pricing_region");
