CREATE TABLE IF NOT EXISTS "AmazonMemoryDB_ingestion" (
    "sku" TEXT,
    "offer_term_code" TEXT,
    "rate_code" TEXT,
    "term_type" TEXT,
    "price_description" TEXT,
    "effective_date" DATE,
    "starting_range" TEXT,
    "ending_range" TEXT,
    "unit" TEXT,
    "price_per_unit" DECIMAL(20,10),
    "currency" TEXT,
    "related_to" TEXT,
    "lease_contract_length" TEXT,
    "purchase_option" TEXT,
    "offering_class" TEXT,
    "product_family" TEXT,
    "service_code" TEXT,
    "location" TEXT,
    "location_type" TEXT,
    "instance_type" TEXT,
    "current_generation" TEXT,
    "instance_family" TEXT,
    "v_cpu" TEXT,
    "memory" TEXT,
    "network_performance" TEXT,
    "storage_media" TEXT,
    "transfer_type" TEXT,
    "usage_type" TEXT,
    "operation" TEXT,
    "engine" TEXT,
    "normalization_size_factor" TEXT,
    "region_code" TEXT,
    "service_name" TEXT,
    "ssd" TEXT,
    "type" TEXT,
    "pricing_region" TEXT NOT NULL,
    PRIMARY KEY (rate_code, pricing_region)
);
CREATE INDEX IF NOT EXISTS AmazonMemoryDB_20250326233433_sku ON "AmazonMemoryDB_ingestion" ("sku");
CREATE INDEX IF NOT EXISTS AmazonMemoryDB_20250326233433_region_code ON "AmazonMemoryDB_ingestion" ("region_code");
CREATE INDEX IF NOT EXISTS AmazonMemoryDB_20250326233433_pricing_region ON "AmazonMemoryDB_ingestion" ("pricing_region");
