CREATE TABLE amazon_game_lift_streams_ingestion (
    "sku" TEXT,
    "offer_term_code" TEXT,
    "rate_code" TEXT PRIMARY KEY,
    "term_type" TEXT,
    "price_description" TEXT,
    "effective_date" DATE,
    "starting_range" TEXT,
    "ending_range" TEXT,
    "unit" TEXT,
    "price_per_unit" DECIMAL(20,10),
    "currency" TEXT,
    "product_family" TEXT,
    "service_code" TEXT,
    "location" TEXT,
    "location_type" TEXT,
    "vcpu" TEXT,
    "storage_class" TEXT,
    "usage_type" TEXT,
    "operation" TEXT,
    "gpu" TEXT,
    "ram" TEXT,
    "region_code" TEXT,
    "reservation_class" TEXT,
    "service_name" TEXT,
    "stream_class" TEXT,
    "vram" TEXT
);
CREATE INDEX amazon_game_lift_streams_20260304231114_sku ON amazon_game_lift_streams_ingestion (sku);
CREATE INDEX amazon_game_lift_streams_20260304231114_region_code ON amazon_game_lift_streams_ingestion (region_code);
