CREATE TABLE IF NOT EXISTS "AmazonCloudFront_ingestion" (
    "sku" TEXT,
    "offer_term_code" TEXT,
    "rate_code" TEXT,
    "term_type" TEXT,
    "price_description" TEXT,
    "effective_date" DATE,
    "starting_range" TEXT,
    "ending_range" TEXT,
    "unit" TEXT,
    "price_per_unit" DECIMAL(20,10),
    "currency" TEXT,
    "product_family" TEXT,
    "service_code" TEXT,
    "location" TEXT,
    "location_type" TEXT,
    "group" TEXT,
    "group_description" TEXT,
    "transfer_type" TEXT,
    "from_location" TEXT,
    "from_location_type" TEXT,
    "to_location" TEXT,
    "to_location_type" TEXT,
    "usage_type" TEXT,
    "operation" TEXT,
    "from_region_code" TEXT,
    "region_code" TEXT,
    "request_description" TEXT,
    "request_type" TEXT,
    "service_name" TEXT,
    "to_region_code" TEXT,
    "pricing_region" TEXT NOT NULL,
    PRIMARY KEY (rate_code, pricing_region)
);
CREATE INDEX IF NOT EXISTS AmazonCloudFront_20250701211647_sku ON "AmazonCloudFront_ingestion" ("sku");
CREATE INDEX IF NOT EXISTS AmazonCloudFront_20250701211647_region_code ON "AmazonCloudFront_ingestion" ("region_code");
CREATE INDEX IF NOT EXISTS AmazonCloudFront_20250701211647_pricing_region ON "AmazonCloudFront_ingestion" ("pricing_region");
