CREATE TABLE amazon_lightsail_ingestion (
    "sku" TEXT,
    "offer_term_code" TEXT,
    "rate_code" TEXT PRIMARY KEY,
    "term_type" TEXT,
    "price_description" TEXT,
    "effective_date" DATE,
    "starting_range" TEXT,
    "ending_range" TEXT,
    "unit" TEXT,
    "price_per_unit" DECIMAL(20,10),
    "currency" TEXT,
    "product_family" TEXT,
    "service_code" TEXT,
    "location" TEXT,
    "location_type" TEXT,
    "v_cpu" TEXT,
    "memory" TEXT,
    "storage" TEXT,
    "operating_system" TEXT,
    "group" TEXT,
    "group_description" TEXT,
    "transfer_type" TEXT,
    "from_location" TEXT,
    "from_location_type" TEXT,
    "to_location" TEXT,
    "to_location_type" TEXT,
    "usage_type" TEXT,
    "operation" TEXT,
    "counts_against_quota" TEXT,
    "data_transfer_quota" TEXT,
    "engine" TEXT,
    "free_overage" TEXT,
    "from_region_code" TEXT,
    "high_availability" TEXT,
    "instance_family" TEXT,
    "is_free" TEXT,
    "overage_type" TEXT,
    "power" TEXT,
    "region_code" TEXT,
    "service_name" TEXT,
    "storage_capacity_quota" TEXT,
    "to_region_code" TEXT
);
CREATE INDEX amazon_lightsail_20260410200730_sku ON amazon_lightsail_ingestion (sku);
CREATE INDEX amazon_lightsail_20260410200730_region_code ON amazon_lightsail_ingestion (region_code);
