CREATE TABLE amazon_es_ingestion (
    "sku" TEXT,
    "offer_term_code" TEXT,
    "rate_code" TEXT PRIMARY KEY,
    "term_type" TEXT,
    "price_description" TEXT,
    "effective_date" DATE,
    "starting_range" TEXT,
    "ending_range" TEXT,
    "unit" TEXT,
    "price_per_unit" DECIMAL(20,10),
    "currency" TEXT,
    "lease_contract_length" INTEGER,
    "purchase_option" TEXT,
    "offering_class" TEXT,
    "product_family" TEXT,
    "service_code" TEXT,
    "location" TEXT,
    "location_type" TEXT,
    "instance_type" TEXT,
    "current_generation" TEXT,
    "instance_family" TEXT,
    "v_cpu" TEXT,
    "storage" TEXT,
    "storage_media" TEXT,
    "usage_type" TEXT,
    "operation" TEXT,
    "compute_type" TEXT,
    "ecu" TEXT,
    "memory_gi_b" TEXT,
    "region_code" TEXT,
    "requests" TEXT,
    "service_name" TEXT
);
CREATE INDEX amazon_es_20260422024050_sku ON amazon_es_ingestion (sku);
CREATE INDEX amazon_es_20260422024050_region_code ON amazon_es_ingestion (region_code);
