CREATE TABLE aws_media_connect_ingestion (
    "sku" TEXT,
    "offer_term_code" TEXT,
    "rate_code" TEXT PRIMARY KEY,
    "term_type" TEXT,
    "price_description" TEXT,
    "effective_date" DATE,
    "starting_range" TEXT,
    "ending_range" TEXT,
    "unit" TEXT,
    "price_per_unit" DECIMAL(20,10),
    "currency" TEXT,
    "product_family" TEXT,
    "service_code" TEXT,
    "location" TEXT,
    "location_type" TEXT,
    "transfer_type" TEXT,
    "from_location" TEXT,
    "from_location_type" TEXT,
    "to_location" TEXT,
    "to_location_type" TEXT,
    "usage_type" TEXT,
    "operation" TEXT,
    "flow_type" TEXT,
    "from_region_code" TEXT,
    "input_tier" TEXT,
    "output_tier" TEXT,
    "region_code" TEXT,
    "reserved_tier" TEXT,
    "router_transfer_type" TEXT,
    "service_name" TEXT,
    "to_region_code" TEXT
);
CREATE INDEX aws_media_connect_20260130171842_sku ON aws_media_connect_ingestion (sku);
CREATE INDEX aws_media_connect_20260130171842_region_code ON aws_media_connect_ingestion (region_code);
