CREATE TABLE aws_interconnect_ingestion (
    "sku" TEXT,
    "offer_term_code" TEXT,
    "rate_code" TEXT PRIMARY KEY,
    "term_type" TEXT,
    "price_description" TEXT,
    "effective_date" DATE,
    "starting_range" TEXT,
    "ending_range" TEXT,
    "unit" TEXT,
    "price_per_unit" DECIMAL(20,10),
    "currency" TEXT,
    "product_family" TEXT,
    "service_code" TEXT,
    "location" TEXT,
    "location_type" TEXT,
    "usage_type" TEXT,
    "operation" TEXT,
    "interconnect_region_billing_prefix" TEXT,
    "interconnect_region_name" TEXT,
    "interconnect_tier" TEXT,
    "partner_cloud_service_provider" TEXT,
    "partner_metro" TEXT,
    "region_code" TEXT,
    "service_name" TEXT,
    "to_region_name" TEXT,
    "traffic_direction" TEXT
);
CREATE INDEX aws_interconnect_20260414235556_sku ON aws_interconnect_ingestion (sku);
CREATE INDEX aws_interconnect_20260414235556_region_code ON aws_interconnect_ingestion (region_code);
