CREATE TABLE aws_systems_manager_ingestion (
    "sku" TEXT,
    "offer_term_code" TEXT,
    "rate_code" TEXT PRIMARY KEY,
    "term_type" TEXT,
    "price_description" TEXT,
    "effective_date" DATE,
    "starting_range" TEXT,
    "ending_range" TEXT,
    "unit" TEXT,
    "price_per_unit" DECIMAL(20,10),
    "currency" TEXT,
    "product_family" TEXT,
    "service_code" TEXT,
    "location" TEXT,
    "location_type" TEXT,
    "storage" TEXT,
    "usage_type" TEXT,
    "operation" TEXT,
    "api_requests_free" TEXT,
    "api_requests_paid" TEXT,
    "change_requests_free" TEXT,
    "change_requests_paid" TEXT,
    "data_transfer" TEXT,
    "describes" TEXT,
    "gets" TEXT,
    "instances" TEXT,
    "ops_items" TEXT,
    "parameter_type" TEXT,
    "region_code" TEXT,
    "response" TEXT,
    "service_name" TEXT,
    "throughput" TEXT,
    "updates" TEXT
);
CREATE INDEX aws_systems_manager_20250828153807_sku ON aws_systems_manager_ingestion (sku);
CREATE INDEX aws_systems_manager_20250828153807_region_code ON aws_systems_manager_ingestion (region_code);
