CREATE TABLE aws_database_migration_svc_ingestion (
    "sku" TEXT,
    "offer_term_code" TEXT,
    "rate_code" TEXT PRIMARY KEY,
    "term_type" TEXT,
    "price_description" TEXT,
    "effective_date" DATE,
    "starting_range" TEXT,
    "ending_range" TEXT,
    "unit" TEXT,
    "price_per_unit" DECIMAL(20,10),
    "currency" TEXT,
    "related_to" TEXT,
    "product_family" TEXT,
    "service_code" TEXT,
    "location" TEXT,
    "location_type" TEXT,
    "instance_type" TEXT,
    "current_generation" TEXT,
    "instance_family" TEXT,
    "v_cpu" TEXT,
    "physical_processor" TEXT,
    "clock_speed" TEXT,
    "memory" TEXT,
    "storage" TEXT,
    "network_performance" TEXT,
    "processor_architecture" TEXT,
    "storage_media" TEXT,
    "volume_type" TEXT,
    "min_volume_size" TEXT,
    "max_volume_size" TEXT,
    "usage_type" TEXT,
    "operation" TEXT,
    "availability_zone" TEXT,
    "capacity_usage" TEXT,
    "dedicated_ebs_throughput" TEXT,
    "enhanced_networking_supported" TEXT,
    "processor_features" TEXT,
    "region_code" TEXT,
    "service_name" TEXT,
    "type" TEXT
);
CREATE INDEX aws_database_migration_svc_20251117230913_sku ON aws_database_migration_svc_ingestion (sku);
CREATE INDEX aws_database_migration_svc_20251117230913_region_code ON aws_database_migration_svc_ingestion (region_code);
