CREATE TABLE aws_backup_ingestion (
    "sku" TEXT,
    "offer_term_code" TEXT,
    "rate_code" TEXT PRIMARY KEY,
    "term_type" TEXT,
    "price_description" TEXT,
    "effective_date" DATE,
    "starting_range" TEXT,
    "ending_range" TEXT,
    "unit" TEXT,
    "price_per_unit" DECIMAL(20,10),
    "currency" TEXT,
    "product_family" TEXT,
    "service_code" TEXT,
    "location" TEXT,
    "location_type" TEXT,
    "to_location" TEXT,
    "to_location_type" TEXT,
    "usage_type" TEXT,
    "operation" TEXT,
    "backup_service" TEXT,
    "backup_action" TEXT,
    "backup_evaluations" TEXT,
    "backup_resource_type" TEXT,
    "index_type" TEXT,
    "region_code" TEXT,
    "search_type" TEXT,
    "service_name" TEXT,
    "storage_tier" TEXT,
    "storage_type" TEXT,
    "storage_type" TEXT,
    "to_region_code" TEXT,
    "vault_type" TEXT
);
CREATE INDEX aws_backup_20260413181745_sku ON aws_backup_ingestion (sku);
CREATE INDEX aws_backup_20260413181745_region_code ON aws_backup_ingestion (region_code);
