CREATE TABLE aws_elemental_media_live_ingestion (
    "sku" TEXT,
    "offer_term_code" TEXT,
    "rate_code" TEXT PRIMARY KEY,
    "term_type" TEXT,
    "price_description" TEXT,
    "effective_date" DATE,
    "starting_range" TEXT,
    "ending_range" TEXT,
    "unit" TEXT,
    "price_per_unit" DECIMAL(20,10),
    "currency" TEXT,
    "product_family" TEXT,
    "service_code" TEXT,
    "location" TEXT,
    "location_type" TEXT,
    "usage_type" TEXT,
    "operation" TEXT,
    "bit_rate" TEXT,
    "codec" TEXT,
    "frame_rate" TEXT,
    "input" TEXT,
    "output" TEXT,
    "pipeline" TEXT,
    "region_code" TEXT,
    "reserve_type" TEXT,
    "resolution" TEXT,
    "service_name" TEXT,
    "video_quality" TEXT
);
CREATE INDEX aws_elemental_media_live_20260220032915_sku ON aws_elemental_media_live_ingestion (sku);
CREATE INDEX aws_elemental_media_live_20260220032915_region_code ON aws_elemental_media_live_ingestion (region_code);
