CREATE TABLE aws_outposts_ingestion (
    "sku" TEXT,
    "offer_term_code" TEXT,
    "rate_code" TEXT PRIMARY KEY,
    "term_type" TEXT,
    "price_description" TEXT,
    "effective_date" DATE,
    "starting_range" TEXT,
    "ending_range" TEXT,
    "unit" TEXT,
    "price_per_unit" DECIMAL(20,10),
    "currency" TEXT,
    "product_family" TEXT,
    "service_code" TEXT,
    "location" TEXT,
    "location_type" TEXT,
    "instance_type" TEXT,
    "current_generation" TEXT,
    "instance_family" TEXT,
    "v_cpu" TEXT,
    "physical_processor" TEXT,
    "clock_speed" TEXT,
    "memory" TEXT,
    "storage" TEXT,
    "network_performance" TEXT,
    "processor_architecture" TEXT,
    "tenancy" TEXT,
    "operating_system" TEXT,
    "license_model" TEXT,
    "usage_type" TEXT,
    "operation" TEXT,
    "capacity_status" TEXT,
    "dedicated_ebs_throughput" TEXT,
    "ecu" TEXT,
    "enhanced_networking_supported" TEXT,
    "gpu" TEXT,
    "gpu_memory" TEXT,
    "intel_avx2_available" TEXT,
    "intel_avx_available" TEXT,
    "intel_turbo_available" TEXT,
    "normalization_size_factor" TEXT,
    "plato_usage_type" TEXT,
    "pre_installed_s_w" TEXT,
    "processor_features" TEXT,
    "region_code" TEXT,
    "service_name" TEXT
);
CREATE INDEX aws_outposts_20251014223447_sku ON aws_outposts_ingestion (sku);
CREATE INDEX aws_outposts_20251014223447_region_code ON aws_outposts_ingestion (region_code);
