CREATE TABLE aws_developer_support_ingestion (
    "sku" TEXT,
    "offer_term_code" TEXT,
    "rate_code" TEXT PRIMARY KEY,
    "term_type" TEXT,
    "price_description" TEXT,
    "effective_date" DATE,
    "starting_range" TEXT,
    "ending_range" TEXT,
    "unit" TEXT,
    "price_per_unit" DECIMAL(20,10),
    "currency" TEXT,
    "product_family" TEXT,
    "service_code" TEXT,
    "location" TEXT,
    "location_type" TEXT,
    "usage_type" TEXT,
    "operation" TEXT,
    "account_assistance" TEXT,
    "architectural_review" TEXT,
    "architecture_support" TEXT,
    "best_practices" TEXT,
    "case_severity_response_times" TEXT,
    "customer_service_and_communities" TEXT,
    "included_services" TEXT,
    "launch_support" TEXT,
    "operations_support" TEXT,
    "proactive_guidance" TEXT,
    "programmatic_case_management" TEXT,
    "region_code" TEXT,
    "service_name" TEXT,
    "technical_support" TEXT,
    "third_party_software_support" TEXT,
    "training" TEXT,
    "who_can_open_cases" TEXT
);
CREATE INDEX aws_developer_support_20230126102445_sku ON aws_developer_support_ingestion (sku);
CREATE INDEX aws_developer_support_20230126102445_region_code ON aws_developer_support_ingestion (region_code);
