CREATE TABLE aws_direct_connect_ingestion (
    "sku" TEXT,
    "offer_term_code" TEXT,
    "rate_code" TEXT PRIMARY KEY,
    "term_type" TEXT,
    "price_description" TEXT,
    "effective_date" DATE,
    "starting_range" TEXT,
    "ending_range" TEXT,
    "unit" TEXT,
    "price_per_unit" DECIMAL(20,10),
    "currency" TEXT,
    "product_family" TEXT,
    "service_code" TEXT,
    "location" TEXT,
    "location_type" TEXT,
    "transfer_type" TEXT,
    "from_location" TEXT,
    "from_location_type" TEXT,
    "to_location" TEXT,
    "to_location_type" TEXT,
    "usage_type" TEXT,
    "operation" TEXT,
    "alpha_3_country_code" TEXT,
    "capacity" TEXT,
    "connection_type" TEXT,
    "continent" TEXT,
    "country" TEXT,
    "direct_connect_location" TEXT,
    "from_region_code" TEXT,
    "geo_region_code" TEXT,
    "port_speed" TEXT,
    "region_code" TEXT,
    "service_name" TEXT,
    "to_region_code" TEXT,
    "version" TEXT,
    "virtual_interface_type" TEXT
);
CREATE INDEX aws_direct_connect_20260326142940_sku ON aws_direct_connect_ingestion (sku);
CREATE INDEX aws_direct_connect_20260326142940_region_code ON aws_direct_connect_ingestion (region_code);
