CREATE TABLE IF NOT EXISTS "AWSDataTransfer_ingestion" (
    "sku" TEXT,
    "offer_term_code" TEXT,
    "rate_code" TEXT,
    "term_type" TEXT,
    "price_description" TEXT,
    "effective_date" DATE,
    "starting_range" TEXT,
    "ending_range" TEXT,
    "unit" TEXT,
    "price_per_unit" DECIMAL(20,10),
    "currency" TEXT,
    "related_to" TEXT,
    "product_family" TEXT,
    "service_code" TEXT,
    "transfer_type" TEXT,
    "from_location" TEXT,
    "from_location_type" TEXT,
    "to_location" TEXT,
    "to_location_type" TEXT,
    "usage_type" TEXT,
    "operation" TEXT,
    "from_region_code" TEXT,
    "service_name" TEXT,
    "to_region_code" TEXT,
    "pricing_region" TEXT NOT NULL,
    PRIMARY KEY (rate_code, pricing_region)
);
CREATE INDEX IF NOT EXISTS AWSDataTransfer_20260427200150_sku ON "AWSDataTransfer_ingestion" ("sku");
CREATE INDEX IF NOT EXISTS AWSDataTransfer_20260427200150_pricing_region ON "AWSDataTransfer_ingestion" ("pricing_region");
