CREATE TABLE IF NOT EXISTS "AWSElementalMediaLive_ingestion" (
    "sku" TEXT,
    "offer_term_code" TEXT,
    "rate_code" TEXT,
    "term_type" TEXT,
    "price_description" TEXT,
    "effective_date" DATE,
    "starting_range" TEXT,
    "ending_range" TEXT,
    "unit" TEXT,
    "price_per_unit" DECIMAL(20,10),
    "currency" TEXT,
    "product_family" TEXT,
    "service_code" TEXT,
    "location" TEXT,
    "location_type" TEXT,
    "usage_type" TEXT,
    "operation" TEXT,
    "bit_rate" TEXT,
    "codec" TEXT,
    "frame_rate" TEXT,
    "input" TEXT,
    "output" TEXT,
    "pipeline" TEXT,
    "region_code" TEXT,
    "reserve_type" TEXT,
    "resolution" TEXT,
    "service_name" TEXT,
    "video_quality" TEXT,
    "pricing_region" TEXT NOT NULL,
    PRIMARY KEY (rate_code, pricing_region)
);
CREATE INDEX IF NOT EXISTS AWSElementalMediaLive_20260220032915_sku ON "AWSElementalMediaLive_ingestion" ("sku");
CREATE INDEX IF NOT EXISTS AWSElementalMediaLive_20260220032915_region_code ON "AWSElementalMediaLive_ingestion" ("region_code");
CREATE INDEX IF NOT EXISTS AWSElementalMediaLive_20260220032915_pricing_region ON "AWSElementalMediaLive_ingestion" ("pricing_region");
