CREATE TABLE IF NOT EXISTS "AWSSecurityHub_ingestion" (
    "sku" TEXT,
    "offer_term_code" TEXT,
    "rate_code" TEXT,
    "term_type" TEXT,
    "price_description" TEXT,
    "effective_date" DATE,
    "starting_range" TEXT,
    "ending_range" TEXT,
    "unit" TEXT,
    "price_per_unit" DECIMAL(20,10),
    "currency" TEXT,
    "product_family" TEXT,
    "service_code" TEXT,
    "location" TEXT,
    "location_type" TEXT,
    "usage_type" TEXT,
    "operation" TEXT,
    "automation_group" TEXT,
    "automation_storage" TEXT,
    "aws_security_hub_v2_cloud_trail_event_monitoring_usage_metered" TEXT,
    "aws_security_hub_v2_essentials_usage_metered" TEXT,
    "aws_security_hub_v2_lambda_code_scanning_usage_metered" TEXT,
    "aws_security_hub_v2_log_monitoring_usage_metered" TEXT,
    "finding_group" TEXT,
    "finding_source" TEXT,
    "finding_storage" TEXT,
    "region_code" TEXT,
    "service_name" TEXT,
    "standard_group" TEXT,
    "standard_storage" TEXT,
    "pricing_region" TEXT NOT NULL,
    PRIMARY KEY (rate_code, pricing_region)
);
CREATE INDEX IF NOT EXISTS AWSSecurityHub_20260330170323_sku ON "AWSSecurityHub_ingestion" ("sku");
CREATE INDEX IF NOT EXISTS AWSSecurityHub_20260330170323_region_code ON "AWSSecurityHub_ingestion" ("region_code");
CREATE INDEX IF NOT EXISTS AWSSecurityHub_20260330170323_pricing_region ON "AWSSecurityHub_ingestion" ("pricing_region");
