CREATE TABLE IF NOT EXISTS "AWSSystemsManager_ingestion" (
    "sku" TEXT,
    "offer_term_code" TEXT,
    "rate_code" TEXT,
    "term_type" TEXT,
    "price_description" TEXT,
    "effective_date" DATE,
    "starting_range" TEXT,
    "ending_range" TEXT,
    "unit" TEXT,
    "price_per_unit" DECIMAL(20,10),
    "currency" TEXT,
    "product_family" TEXT,
    "service_code" TEXT,
    "location" TEXT,
    "location_type" TEXT,
    "storage" TEXT,
    "usage_type" TEXT,
    "operation" TEXT,
    "api_requests_free" TEXT,
    "api_requests_paid" TEXT,
    "change_requests_free" TEXT,
    "change_requests_paid" TEXT,
    "data_transfer" TEXT,
    "describes" TEXT,
    "gets" TEXT,
    "instances" TEXT,
    "ops_items" TEXT,
    "parameter_type" TEXT,
    "region_code" TEXT,
    "response" TEXT,
    "service_name" TEXT,
    "throughput" TEXT,
    "updates" TEXT,
    "pricing_region" TEXT NOT NULL,
    PRIMARY KEY (rate_code, pricing_region)
);
CREATE INDEX IF NOT EXISTS AWSSystemsManager_20250828153807_sku ON "AWSSystemsManager_ingestion" ("sku");
CREATE INDEX IF NOT EXISTS AWSSystemsManager_20250828153807_region_code ON "AWSSystemsManager_ingestion" ("region_code");
CREATE INDEX IF NOT EXISTS AWSSystemsManager_20250828153807_pricing_region ON "AWSSystemsManager_ingestion" ("pricing_region");
