CREATE TABLE IF NOT EXISTS "AWSShield_ingestion" (
    "sku" TEXT,
    "offer_term_code" TEXT,
    "rate_code" TEXT PRIMARY KEY,
    "term_type" TEXT,
    "price_description" TEXT,
    "effective_date" DATE,
    "starting_range" TEXT,
    "ending_range" TEXT,
    "unit" TEXT,
    "price_per_unit" DECIMAL(20,10),
    "currency" TEXT,
    "product_family" TEXT,
    "service_code" TEXT,
    "from_location" TEXT,
    "from_location_type" TEXT,
    "to_location" TEXT,
    "to_location_type" TEXT,
    "usage_type" TEXT,
    "operation" TEXT,
    "from_region_code" TEXT,
    "resource_type" TEXT,
    "service_name" TEXT,
    "to_region_code" TEXT
);
CREATE INDEX IF NOT EXISTS AWSShield_20250508181231_sku ON "AWSShield_ingestion" ("sku");
