CREATE TABLE code_build_ingestion (
    "sku" TEXT,
    "offer_term_code" TEXT,
    "rate_code" TEXT PRIMARY KEY,
    "term_type" TEXT,
    "price_description" TEXT,
    "effective_date" DATE,
    "starting_range" TEXT,
    "ending_range" TEXT,
    "unit" TEXT,
    "price_per_unit" DECIMAL(20,10),
    "currency" TEXT,
    "related_to" TEXT,
    "product_family" TEXT,
    "service_code" TEXT,
    "location" TEXT,
    "location_type" TEXT,
    "v_cpu" TEXT,
    "memory" TEXT,
    "operating_system" TEXT,
    "usage_type" TEXT,
    "operation" TEXT,
    "architecture" TEXT,
    "compute_family" TEXT,
    "compute_type" TEXT,
    "region_code" TEXT,
    "service_name" TEXT,
    "storage_family" TEXT,
    "storage_type" TEXT
);
CREATE INDEX code_build_20250610165933_sku ON code_build_ingestion (sku);
CREATE INDEX code_build_20250610165933_region_code ON code_build_ingestion (region_code);
