CREATE TABLE IF NOT EXISTS "IngestionServiceSnowball_ingestion" (
    "sku" TEXT,
    "offer_term_code" TEXT,
    "rate_code" TEXT,
    "term_type" TEXT,
    "price_description" TEXT,
    "effective_date" DATE,
    "starting_range" TEXT,
    "ending_range" TEXT,
    "unit" TEXT,
    "price_per_unit" DECIMAL(20,10),
    "currency" TEXT,
    "product_family" TEXT,
    "service_code" TEXT,
    "location" TEXT,
    "location_type" TEXT,
    "group" TEXT,
    "group_description" TEXT,
    "transfer_type" TEXT,
    "from_location" TEXT,
    "from_location_type" TEXT,
    "to_location" TEXT,
    "to_location_type" TEXT,
    "usage_type" TEXT,
    "operation" TEXT,
    "device_description" TEXT,
    "extra_day_fee" TEXT,
    "free_days" TEXT,
    "from_region_code" TEXT,
    "job_n_shipp" TEXT,
    "job_fee" TEXT,
    "plato_snowball_type" TEXT,
    "region_code" TEXT,
    "release_type" TEXT,
    "service_name" TEXT,
    "snowball_type" TEXT,
    "to_region_code" TEXT,
    "pricing_region" TEXT NOT NULL,
    PRIMARY KEY (rate_code, pricing_region)
);
CREATE INDEX IF NOT EXISTS IngestionServiceSnowball_20251218221255_sku ON "IngestionServiceSnowball_ingestion" ("sku");
CREATE INDEX IF NOT EXISTS IngestionServiceSnowball_20251218221255_region_code ON "IngestionServiceSnowball_ingestion" ("region_code");
CREATE INDEX IF NOT EXISTS IngestionServiceSnowball_20251218221255_pricing_region ON "IngestionServiceSnowball_ingestion" ("pricing_region");
