CREATE TABLE ingestion_service_snowball_ingestion (
    "sku" TEXT,
    "offer_term_code" TEXT,
    "rate_code" TEXT PRIMARY KEY,
    "term_type" TEXT,
    "price_description" TEXT,
    "effective_date" DATE,
    "starting_range" TEXT,
    "ending_range" TEXT,
    "unit" TEXT,
    "price_per_unit" DECIMAL(20,10),
    "currency" TEXT,
    "product_family" TEXT,
    "service_code" TEXT,
    "location" TEXT,
    "location_type" TEXT,
    "group" TEXT,
    "group_description" TEXT,
    "transfer_type" TEXT,
    "from_location" TEXT,
    "from_location_type" TEXT,
    "to_location" TEXT,
    "to_location_type" TEXT,
    "usage_type" TEXT,
    "operation" TEXT,
    "device_description" TEXT,
    "extra_day_fee" TEXT,
    "free_days" TEXT,
    "from_region_code" TEXT,
    "job_n_shipp" TEXT,
    "job_fee" TEXT,
    "plato_snowball_type" TEXT,
    "region_code" TEXT,
    "release_type" TEXT,
    "service_name" TEXT,
    "snowball_type" TEXT,
    "to_region_code" TEXT
);
CREATE INDEX ingestion_service_snowball_20251218221255_sku ON ingestion_service_snowball_ingestion (sku);
CREATE INDEX ingestion_service_snowball_20251218221255_region_code ON ingestion_service_snowball_ingestion (region_code);
