CREATE TABLE IF NOT EXISTS "Kiro_ingestion" (
    "sku" TEXT,
    "offer_term_code" TEXT,
    "rate_code" TEXT PRIMARY KEY,
    "term_type" TEXT,
    "price_description" TEXT,
    "effective_date" DATE,
    "starting_range" TEXT,
    "ending_range" TEXT,
    "unit" TEXT,
    "price_per_unit" DECIMAL(20,10),
    "currency" TEXT,
    "service_code" TEXT,
    "location" TEXT,
    "location_type" TEXT,
    "usage_type" TEXT,
    "operation" TEXT,
    "feature_code_credits" TEXT,
    "feature_name_credits" TEXT,
    "feature_sku_credits" TEXT,
    "overage_price_per_unit_credits" TEXT,
    "plan_code" TEXT,
    "plan_family_code" TEXT,
    "plan_family_name" TEXT,
    "plan_name" TEXT,
    "region_code" TEXT,
    "service_name" TEXT,
    "usage_pooling_policy_credits" TEXT,
    "usage_quota_credits" TEXT,
    "usage_quota_unit_credits" TEXT
);
CREATE INDEX IF NOT EXISTS Kiro_20260414131706_sku ON "Kiro_ingestion" ("sku");
CREATE INDEX IF NOT EXISTS Kiro_20260414131706_region_code ON "Kiro_ingestion" ("region_code");
