CREATE TABLE IF NOT EXISTS "nimble_ingestion" (
    "sku" TEXT,
    "offer_term_code" TEXT,
    "rate_code" TEXT,
    "term_type" TEXT,
    "price_description" TEXT,
    "effective_date" DATE,
    "starting_range" TEXT,
    "ending_range" TEXT,
    "unit" TEXT,
    "price_per_unit" DECIMAL(20,10),
    "currency" TEXT,
    "product_family" TEXT,
    "service_code" TEXT,
    "location" TEXT,
    "location_type" TEXT,
    "instance_type" TEXT,
    "v_cpu" TEXT,
    "memory" TEXT,
    "storage_media" TEXT,
    "volume_type" TEXT,
    "max_iops_volume" TEXT,
    "max_throughput_volume" TEXT,
    "provisioned" TEXT,
    "operating_system" TEXT,
    "group" TEXT,
    "group_description" TEXT,
    "usage_type" TEXT,
    "operation" TEXT,
    "maax_volume_size" TEXT,
    "plato_volume_type" TEXT,
    "region_code" TEXT,
    "service_name" TEXT,
    "volume_api_name" TEXT,
    "pricing_region" TEXT NOT NULL,
    PRIMARY KEY (rate_code, pricing_region)
);
CREATE INDEX IF NOT EXISTS nimble_20221221201025_sku ON "nimble_ingestion" ("sku");
CREATE INDEX IF NOT EXISTS nimble_20221221201025_region_code ON "nimble_ingestion" ("region_code");
CREATE INDEX IF NOT EXISTS nimble_20221221201025_pricing_region ON "nimble_ingestion" ("pricing_region");
