CREATE TABLE researchstudio_ingestion (
    "sku" TEXT,
    "offer_term_code" TEXT,
    "rate_code" TEXT PRIMARY KEY,
    "term_type" TEXT,
    "price_description" TEXT,
    "effective_date" DATE,
    "starting_range" TEXT,
    "ending_range" TEXT,
    "unit" TEXT,
    "price_per_unit" DECIMAL(20,10),
    "currency" TEXT,
    "service_code" TEXT,
    "location" TEXT,
    "location_type" TEXT,
    "usage_type" TEXT,
    "operation" TEXT,
    "feature_code_experiment_units" TEXT,
    "feature_name_experiment_units" TEXT,
    "feature_sku_experiment_units" TEXT,
    "overage_price_per_unit_experiment_units" TEXT,
    "plan_code" TEXT,
    "plan_family_code" TEXT,
    "plan_family_name" TEXT,
    "plan_name" TEXT,
    "region_code" TEXT,
    "service_name" TEXT,
    "usage_pooling_policy_experiment_units" TEXT,
    "usage_quota_experiment_units" TEXT,
    "usage_quota_unit_experiment_units" TEXT
);
CREATE INDEX researchstudio_20260414131736_sku ON researchstudio_ingestion (sku);
CREATE INDEX researchstudio_20260414131736_region_code ON researchstudio_ingestion (region_code);
